# Argus System Monitor Configuration Template
# Copy this file to config.yaml and customize for your environment

server:
        port: 8080
        host: "localhost"
        read_timeout: "30s"
        write_timeout: "30s"

debug:
        enabled: true
        pprof_enabled: true
        pprof_path: "/debug/pprof"
        benchmark_enabled: true

monitoring:
        update_interval: "5s"
        metrics_retention: "24h"
        process_limit: 100

alerts:
        enabled: true
        storage_path: "./.argus/alerts"
        notification_interval: "1m"

tasks:
        enabled: true
        storage_path: "./.argus/tasks"
        max_concurrent: 5

storage:
        base_path: "./.argus"
        file_permissions: 0644
        backup_enabled: true

logging:
        level: "info"
        format: "json"
        file: ""

websocket:
        enabled: true
        path: "/ws"
        read_buffer_size: 1024
        write_buffer_size: 1024

cors:
        enabled: true
        allowed_origins: ["http://localhost:3000", "http://localhost:5173"]
        allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allowed_headers: ["Content-Type", "Authorization"]
